In [3]:
l=[12,23,33,45,90,45,98]
print(l)


[12, 23, 33, 45, 90, 45, 98]


In [4]:
import numpy as np

# List vs array

l=[12,23,33,45,90,45,98]
print(l)

import numpy as np 
aar=np.array([12,35,98,78,25])
print(aar)


[12, 23, 33, 45, 90, 45, 98]
[12 35 98 78 25]


In [7]:
aa=np.array([12,56,89,75,25,36,75,12,96,14,78,10,52,34,58,96,19,97,31])
print(aa)

[12 56 89 75 25 36 75 12 96 14 78 10 52 34 58 96 19 97 31]


# 2D Array

In [9]:
a=np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
a=np.array([
            [1,2,3,4,5],
            [10,11,12,45,56],
            [10,11,12,45,56],
            [45,48,79,52,69],
            [78,45,58,96,32]])
print(a)

[[ 1  2  3  4  5]
 [10 11 12 45 56]
 [10 11 12 45 56]
 [45 48 79 52 69]
 [78 45 58 96 32]]


In [11]:
n=np.array([[1,2,3,4,5],
           [6,7,8,9,10],
           [11,12,13,14,15],
           [16,17,18,19,20],
           [21,22,23,24,25]])
print(n)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


## 3 D Array

In [13]:
array_3d=np.array([[[1,2,3],[4,5,6]],
                   [[7,8,9],[10,11,12]],
                  [[13,14,15],[16,17,18]]])
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [14]:
array1=np.array([[[10,11,12,13],[45,89,78,23]],
                [[89,78,14,96],[36,78,73,69]]])
print(array1)

[[[10 11 12 13]
  [45 89 78 23]]

 [[89 78 14 96]
  [36 78 73 69]]]


In [15]:
# creating arrays for zeros

s=np.zeros((5,5))
print(s)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
# creating array of one 
s=np.ones((200,5))
print(s)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1.

In [17]:
## identity matrix
s=np.eye((3))
print(s)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
a=np.array([12,56,89,75,25,36,75,12,96,14,78,10,52,34,58,96,19,97,31])
print(a)


[12 56 89 75 25 36 75 12 96 14 78 10 52 34 58 96 19 97 31]


In [19]:
print(np.sum(a))

965


In [20]:
print(np.min(a))

10


In [21]:
print(np.max(a))

97


In [22]:
print(np.sort(a))

[10 12 12 14 19 25 31 34 36 52 56 58 75 75 78 89 96 96 97]


In [23]:
print(np.mean(a))

50.78947368421053


In [24]:
print(np.unique(a))

[10 12 14 19 25 31 34 36 52 56 58 75 78 89 96 97]


In [25]:
a =np.array([12 ,16, 14 ,35])

b =np.array([3 ,2 ,4 ,7])

 

In [26]:
print(a-b)

[ 9 14 10 28]


In [27]:
print(a*b)

[ 36  32  56 245]


In [28]:
print(a/b)

[4.  8.  3.5 5. ]


In [29]:
print(a%b)

[0 0 2 0]


In [30]:
print(a**b)

[     1728       256     38416 -85212565]


# Indexing and spicing 

In [32]:
ar=np.array([10,20,30,40,50,60,70,80,90,100])
print(ar)

[ 10  20  30  40  50  60  70  80  90 100]


In [33]:
print(ar[0])

10


In [34]:
print(ar[1])

20


In [35]:
print(ar[2])

30


In [36]:
print(ar[3])

40


In [37]:
print(ar[-1])

100


In [38]:
print(ar[-2])

90


In [39]:
print(ar[-3])

80


In [40]:
print(ar[-4])

70


In [41]:
print(ar[-5])

60


In [42]:
print(ar[1:5])

[20 30 40 50]


In [43]:
print(ar[0:4])

[10 20 30 40]


In [44]:
print(ar[5:7])

[60 70]


In [45]:
print(ar[1::]) # or print(ar[1:])

[ 20  30  40  50  60  70  80  90 100]


In [46]:
print(ar[: 5])

[10 20 30 40 50]


In [47]:
print(ar[: 4])

[10 20 30 40]


# Fancy indexing

In [49]:
arr=np.array([10,20,30,85,759,7863,15,961])
arr[arr <34] = 56
print(arr)

[  56   56   56   85  759 7863   56  961]


In [50]:
ar=np.array([10,20,30,85,759,7863,15,961])
ar[ar >80 ]=95
print(ar)



[10 20 30 95 95 95 15 95]


In [51]:
arr=np.array([1,2,3,4]) # to change order 
order=[2,3,0,1]
print(arr[order])

[3 4 1 2]


In [52]:
arr=np.array([10,20,30,85,759,7863,15,961])
print(arr)


[  10   20   30   85  759 7863   15  961]


In [53]:
print(arr[[2,5,3]])


[  30 7863   85]


In [54]:
print(arr[[3,7]])

[ 85 961]


# Boolean masking 

In [56]:
import numpy as np

ar = np.array([12,34,36,43,45,23,56,78,57,43,12,45,78,8,45,89,87,9,65,32,32])

print(ar[ar >= 56])
 

[56 78 57 78 89 87 65]


In [57]:
import numpy as np

ar = np.array([12,34,36,43,45,23,56,78,57,43,12,45,78,8,45,89,87,9,65,32,32])

print(ar[ar <= 65])
 

[12 34 36 43 45 23 56 57 43 12 45  8 45  9 65 32 32]


In [58]:
import numpy as np

ar = np.array([12,34,36,43,45,23,56,78,57,43,12,45,78,8,45,89,87,9,65,32,32])

count =np.sum(ar>47)

print(count)
 

7


In [59]:
a = np.array([2,4,8,3,9,1])

b = np.where(a % 2 == 0)

print(b)
 

(array([0, 1, 2], dtype=int64),)


In [60]:
import numpy as np

ar = np.array([34,56,87,98,55,87,76,76,87,34,62,62,23,67,65,71,98])

mask =(ar> 45) & (ar < 79)

print(ar[mask])
 

[56 55 76 76 62 62 67 65 71]


In [61]:
# 1. Create a NumPy array `arr = np.array([1, 2, 3, 4, 5])`. Extract the elements at indices 1 and 3 using indexing.

arr = np.array([1, 2, 3, 4, 5])
print(arr[1])
print(arr[3])



2
4


In [62]:
#2. Create a NumPy array `arr = np.array([[1, 2, 3], [4, 5, 6]])`. Extract the second row using slicing.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1:])


[[4 5 6]]


In [63]:
# 3. Create a NumPy array `arr = np.array([1, 2, 3, 4, 5])`. Extract the elements from index 1 to 3 using slicing.
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])


[2 3 4]


In [64]:
# 4. Create a NumPy array `arr = np.array([1, 2, 3, 4, 5])`. Find the minimum value in the array.
arr = np.array([1, 2, 3, 4, 5])
print(np.min(arr))


1


In [65]:
# 5. Create a NumPy array `arr = np.array([1, 2, 3, 4, 5])`. Find the maximum value in the array.
arr = np.array([1, 2, 3, 4, 5])
print(np.max(arr))


5


In [66]:
# 6. Create a NumPy array `arr = np.array([1, 2, 3, 4, 5])`. Calculate the mean of the array.
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))


3.0


In [67]:
# 7. Create a NumPy array `arr = np.array([1, 2, 3, 4, 5])`. Calculate the sum of the array.
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))


15


In [68]:
# 8. Create a NumPy array `arr = np.array([[1, 2, 3], [4, 5, 6]])`. Find the maximum value in each row.
arr = np.array([[1, 2, 3], [4, 5, 6]])
row1=arr[0]
print(np.max(row1))



3


In [69]:
row2=arr[1]
print(np.max(row2))


6


In [70]:
# 9. Create a NumPy array `arr = np.array([[1, 2, 3], [4, 5, 6]])`. Calculate the mean of each column.

arr = np.array([[1, 2, 3], [4, 5, 6]])
r1=arr[0]
print(np.mean(r1))
r2=arr[1]
print(np.mean(r2))

2.0
5.0


In [71]:
# 10. Create a NumPy array `arr = np.array([1, 2, 3, 4, 5])`. Find the indices of the minimum and maximum values in the array.

arr = np.array([1, 2, 3, 4, 5])
 


# Q1. Create a 1D NumPy array containing numbers from 10 to 19.


In [73]:
lst=np.array([10,11,12,13,14,16,17,18,19])
print(lst)

[10 11 12 13 14 16 17 18 19]


In [74]:
# Q2. Create a 2D NumPy array with 3 rows and 4 columns filled with numbers from 1 to 12.

lst1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(lst1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [75]:
#Q3. Create an array of 6 zeros and another array of 6 ones.
zero=np.zeros(6)
print(zero)

[0. 0. 0. 0. 0. 0.]


In [76]:
zero=np.ones(6)
print(zero)

[1. 1. 1. 1. 1. 1.]


In [117]:
 # Q4. Create a 1D array of even numbers between 20 and 40.
even=np.arange(20,40,2)
print(even)

[20 22 24 26 28 30 32 34 36 38]


In [121]:
# Q5. Create a 3x3 array filled with random integers between 50 and 100.
random_array = np.random.randint(low=50, high=101, size=(3, 3))

print(random_array)

AttributeError: module 'numpy.random' has no attribute 'arange'

In [ ]:
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40])
print(arr[2])
print(arr[5])

In [ ]:
print(arr[1:5])

In [ ]:
print(arr[-4:-1 ])

In [ ]:
ran=np.random.randint(1,50,30)
print(ran)

In [ ]:
ran1=np.random.randint(1,30,10)
ran2=np.random.randint(1,50,10)
print(ran1)
print(ran2)



In [ ]:
print(ran1-ran2)

In [ ]:
print(ran1+ran2)

In [ ]:
print(ran1/ran2)

In [ ]:
print(ran1*ran2)


In [ ]:
data = np.array([100, 200, 300, 400, 500, 600])

print(data[[1,3,4]])


In [ ]:
data[data>400]=350
print(data)

In [ ]:
data = np.array([100, 200, 300, 400, 500, 600])
print(data[data>=300])
print(data)
